project_name: stew

before:
  hooks:
    - go mod tidy

builds:
  - # Build macOS, Linux and Windows versions
    main: ./cmd/main.go
    goos:
      - linux
      - darwin
      - windows
    goarch:
      - amd64
      - arm64
    targets:
      - linux_amd64
      - darwin_amd64
      - darwin_arm64
      - windows_amd64
    env:
      - CGO_ENABLED=0
    ldflags:
      - -s -w
    gobinary: "/usr/local/go/bin/go"

brews:
  - # GitHub/GitLab repository to push the formula to
    tap:
      owner: veda-p
      name: homebrew-stew
      branch: main
    custom_require: "lib/private"
    download_strategy: GitHubPrivateRepositoryReleaseDownloadStrategy
    # Default for github is "https://github.com/<repo_owner>/<repo_name>/releases/download/{{ .Tag }}/{{ .ArtifactName }}"
    url_template: "https://github.com/veda-p/stew/releases/download/{{ .Tag }}/{{ .ArtifactName }}"

    # Git author used to commit to the repository.
    # Defaults are shown.
    commit_author:
      name: veda-p
      email: vedapatil@deloitte.nl

    folder: Formula
    # skip_upload: "true"
    description: "A powerful CLI for the Create and Deploy App project"

    license: "Apache-2.0"

    dependencies:
      - name: terraform
      - name: git
      - name: go
      - name: buildah

archives:
  - # Replacements for GOOS and GOARCH in the archive name.
    replacements:
      darwin: macOS
      linux: Linux
      windows: Windows
      amd64: x86_64

    format_overrides:
      - goos: windows
        format: zip

    files:
      - LICENSE
      - README.md

checksum:
  name_template: "checksums.txt"

snapshot:
  name_template: "{{ .Tag }}"

changelog:
  sort: asc
  filters:
    exclude:
      - "^*.md:"

