# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Stew < Formula
  desc "A powerful CLI for the Create and Deploy App project"
  homepage ""
  version "0.0.2"
  license "Apache-2.0"

  on_macos do
    if Hardware::CPU.arm?
      url "https://github.com/veda-p/stew/releases/download/v0.0.2/stew_0.0.2_macOS_arm64.tar.gz"
      sha256 "7bcfe9f9d3be27ea24a42ee2cffe411c0ddee891582ca6a7c01b1119db9b79c1"

      def install
        bin.install "stew"
      end
    end
    if Hardware::CPU.intel?
      url "https://github.com/veda-p/stew/releases/download/v0.0.2/stew_0.0.2_macOS_x86_64.tar.gz"
      sha256 "0ce56134ada3b1e09f7b68ad495978d2f247d643624e119e80c14152a8f52b25"

      def install
        bin.install "stew"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel?
      url "https://github.com/veda-p/stew/releases/download/v0.0.2/stew_0.0.2_Linux_x86_64.tar.gz"
      sha256 "064433d1250a30d980a81ff62f3337cf7889dc163bd87a8d38edb3df29fe78ff"

      def install
        bin.install "stew"
      end
    end
  end

  depends_on "terraform"
  depends_on "git"
  depends_on "go"
end
